config/routes.rb
BlogApp::Application.routes.draw do
  resources :roles

  devise_for :users, :controllers => { :registrations => "users/registrations" }

  resources :users do 
    member do
     get :edit_password
     put :update_password
    end 
  end 
 

  resources :posts do
    resources :comments
  end

  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :body
  validates :title, presence: true
  validates :body, presence: true
  has_many :comments, dependent: :destroy 
  validates_associated :comments
  
  def self.comments_count
    joins("LEFT OUTER JOIN comments ON comments.post_id = posts.id").select('posts.title, posts.body, posts.id,count(comments) as comments_count').
              group('posts.title, posts.body, posts.id')
  end  
    
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
#  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.comments_count
    
    logger.info "="*30
    logger.info @posts.inspect
    logger.info "="*30
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.includes(:comments).find(params[:id])
    @post = @post.as_json(:include => {
                               :comments => {:only => [:body,:commenter]} 
                               })
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
	</div>
  <% end %>
   

  <div class="actions">
  	 
	  <p>Title: <%= f.text_field :title %></p>
	  <p>Body: <br/>
	  <%= f.text_area :body %></p>
	 	
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Comments Count</th>
  </tr>



<%# @posts.each do |post| %>
  <tr>
  	<td><%# post.title %></td>
	<td><%# post.body %></td>
	<td><%# post.comments.count %></td>
    <td><%# link_to 'Show', post %></td>
    <td><%# link_to 'Edit', edit_post_path(post) %></td>
    <td><%# link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% #end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %> |
<%= link_to 'Manage Users', users_path if current_user.role? :admin%>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h3><b>Title:</b> <%= @post.title %></h3>
<p><b>Body : </b><%= @post.body %></p>
<% if @post.comments.count > 0 %>
<p><strong><u>User Comments:</u></strong></p>
<% @post.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  <p>
  	<%= link_to 'Delete', [comment.post, comment], :method => :delete, :data => {:confirm => 'are u sure?'} %>
  </p>
  
<% end %>
<%end%>

<p><strong>Add Comment:</strong> </p>

<%= form_for([@post, @post.comments.build]) do|f|%>
  <% if @comment && @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<p>User name:<%= f.text_field :commenter, :value => @comment.nil? ? nil : @comment.commenter %></p>
<p>Comment:</p>
<p><%= f.text_area :body, :rows => 5, :cols => 10, :value => @comment.nil? ? nil : @comment.body %></p>
<p><%= f.submit %></p>

<%end%>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>